# Your Task

- Download and import the Data Science Job Salary dataset.
- Normalize the ‘salary’ column using Min-Max normalization which scales all salary values between 0 and 1.
- Implement dimensionality reduction like Principal Component Analysis (PCA) or t-SNE to reduce the number of features (columns) in the dataset.
- Group the dataset by the ‘experience_level’ column and calculate the average and median salary for each experience level (e.g., Junior, Mid-level, Senior).

## Answer

In [1]:
import pandas as pd
import numpy as np
from sklearn.preprocessing import MinMaxScaler
from sklearn.decomposition import PCA
from sklearn.manifold import TSNE

# ================= BASIC WORKFLOW =================

job_salary = pd.read_csv('data/datascience_salaries.csv')

job_salary.head()

,Unnamed: 0,job_title,job_type,experience_level,location,salary_currency,salary
0,0,Data scientist,Full Time,Senior,New York City,USD,149000
1,2,Data scientist,Full Time,Senior,Boston,USD,120000
2,3,Data scientist,Full Time,Senior,London,USD,68000
3,4,Data scientist,Full Time,Senior,Boston,USD,120000
4,5,Data scientist,Full Time,Senior,New York City,USD,149000

In [2]:
job_salary.shape

(1171, 7)

In [3]:
job_salary.info()

<class 'pandas.DataFrame'>
RangeIndex: 1171 entries, 0 to 1170
Data columns (total 7 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Unnamed: 0        1171 non-null   int64
 1   job_title         1171 non-null   str
 2   job_type          1171 non-null   str
 3   experience_level  1171 non-null   str
 4   location          1171 non-null   str
 5   salary_currency   1171 non-null   str
 6   salary            1171 non-null   int64
dtypes: int64(2), str(5)
memory usage: 64.2 KB

In [4]:
job_salary.describe()

        Unnamed: 0         salary
count  1171.000000    1171.000000
mean    931.620837   64836.037575
std     647.445266   32551.767046
min       0.000000   30000.000000
25%     364.500000   45000.000000
50%     815.000000   63000.000000
75%    1504.500000   68000.000000
max    2259.000000  228000.000000

In [5]:
# ================ NORMALIZE SALARY ================

print("\nSalary before MinMaxScaler\n")
print(job_salary['salary'].head())

scaler = MinMaxScaler()
job_salary['salary'] = scaler.fit_transform(job_salary[['salary']])

print("\nSalary after MinMaxScaler\n")
print(job_salary['salary'].head())

Salary before MinMaxScaler

0    149000
1    120000
2     68000
3    120000
4    149000
Name: salary, dtype: int64

Salary after MinMaxScaler

0    0.601010
1    0.454545
2    0.191919
3    0.454545
4    0.601010
Name: salary, dtype: float64

In [6]:
# ================== PCA ==================
# PCA requires numerical data only
# PCA operates on a feature matrix, not a raw DataFrame
numeric_df = job_salary.select_dtypes(include="number")

pca = PCA(n_components=2)
reduced_data = pca.fit_transform(numeric_df)

pca_df = pd.DataFrame(
    reduced_data,
    columns=["PC1", "PC2"]
)

pca_df.head()

          PC1       PC2
0 -931.620836  0.427553
1 -929.620836  0.281083
2 -928.620837  0.018454
3 -927.620836  0.281077
4 -926.620836  0.427539

In [7]:
# ================== Group by the ‘experience_level’ ======================

grouped_df = job_salary.groupby('experience_level')
median_salary = grouped_df['salary'].median()
average_salary = grouped_df['salary'].mean()

print("\nMedian Salary\n")
print(median_salary)
print("\nAverage Salary\n")
print(average_salary)

Median Salary

experience_level
Entry        0.000000
Executive    0.080808
Mid          0.106061
Senior       0.191919
Name: salary, dtype: float64

Average Salary

experience_level
Entry        0.030864
Executive    0.232712
Mid          0.110035
Senior       0.227717
Name: salary, dtype: float64